name: Python application

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build and install package
        run: |
          python app/package/setup.py && rm -vrf *.egg-info ./lib *.win-amd64
          pip install wheels/kommati_para-0.0.1-py3-none-any.whl --force-reinstall

      - name: Print Python Paths
        run: |
          python -c "import sys; print(sys.path)"

      - name: Show Package Info
        run: |
          pip show kommati-para

      - name: Diagnostic Import Test
        run: |
          python -c "import sys; print(sys.path); import kommati_para; print('Import successful')"

#      - name: Run Tests
#        run: python -m pytest app/tests/
