name: Python application

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build and install package
        run: |
          python app/package/setup.py
          pip install dist/*.whl

#      - name: Run Tests
#        run: |
#          pytest app/tests/
